name: Todoist Priority Automation

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Run script
        env:
          TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
        run: python main.py
